[package]
cjc-version = "0.56.4"
compile-option = ""
description = "clang-c binding for cangjie"
link-option = ""
name = "clang_c"
output-type = "static"
override-compile-option = ""
src-dir = ""
target-dir = ""
version = "1.0.0"
package-configuration = {}

[ffi.c]
clang = { path = "./lib" }

[script-dependencies]
glob = { git = "https://github.com/Zxilly/glob-cj.git", branch = "master" }
